version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ssafytrip
      MYSQL_USER: user
      MYSQL_PASSWORD: 1001
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-mysql:3306/ssafytrip
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "80:8080"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:

volumes:
  mysql-data:
